### ISSUE TITLE
Automatically display an image on load

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/facsViewer#2]
Allow me to pass an option that tells facsViewer to display a particular image at presentation size. Maybe the first one in the directory listing/json or an explicitly ref'd file.

**Comment by martindholmes** [comment]
You can just add the id of the image as a hash to the page URL. The image is shown at presentation size by being the :target.

**Comment by martindholmes** [comment]
This is superceded by https://github.com/martindholmes/facsViewer/issues/6.
