### ISSUE TITLE
Allow image listing as local variable 

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/facsViewer#3]
I can pass a path to a JSON file that contains ref's to my images, but I'd also like to pass a ref to an in-page variable that contains the JSON. I hacked the loadJSON function to look like this
`async loadJSON(uri){
	  let strJSON, response;
	  if (typeof uri === 'string') {
		  response = await fetch(uri);
		  strJSON = await response.text();
	  } else {
		  strJSON = JSON.stringify(uri);
	  }
    this.readJSON(strJSON);
  }`
I'm sure there's a more elegant way of handling it.

**Comment by martindholmes** [comment]
That's a good idea. I think it might be better to have a separate function you call with a variable name, rather than having the loadJSON function handle something which is an object rather than JSON. Something like setImages(obj).

**Comment by martindholmes** [comment]
@gtnewton On second thoughts, I'm wondering if you can just do this:

`facsViewer.readJSON(JSON.stringify(myThing));`

I don't see why that wouldn't work, and given how short it is, I don't see the need to add any code to the lib.

**Comment by martindholmes** [comment]
@gtnewton Any thoughts on this? I'm thinking it should be enough just to add an example of this to the documentation, no?

**Comment by gtnewton** [comment]
Yes, I think that'll work a treat.

**Comment by martindholmes** [comment]
Documentation added in commit https://github.com/martindholmes/facsViewer/commit/cf407bba3c9137d87a735dc6706cb63e5ff001cc.
