### ISSUE TITLE
Make the controls (arrows etc.) easier to change

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/facsViewer#4]
They could either be an array that gets passed as an option or handed off to CSS.

**Comment by martindholmes** [comment]
One option is to provide your own template in the page. If it finds your template, it won't add its own. I need to document how to do that, though. It's more flexible generally -- you can change anything you like, then -- but the process that builds the objects from the template needs to be sure that specific things are there in the template, so there would have to be a careful list of things you can't change.

**Comment by martindholmes** [comment]
@gtnewton Would this be satisfied by some documentation on how to add your own template? It seems like that would be the best option, because it allows control over everything. I can make the template-cloning code more amenable to missing items so that you could even delete things such as the zoom buttons completely, and they'd just go away.

**Comment by gtnewton** [comment]
Yes, definitely. I think it'd be a set-it-and-forget-it kind of thing so a short learning curve would be totally acceptable - and that stuff isn't hard to begin with.

**Comment by martindholmes** [comment]
OK, just a question of documentation and testing, then. I'll try to get that done today.

**Comment by martindholmes** [comment]
@gtnewton I've just tested a version of the code where I take care to check the existence of every component when building out the image blocks, and you pay a terrible price in execution time, so I'm going to do this purely through documentation. For cases where users want to suppress things (such as the zoom buttons, for instance) I'll suggest using CSS to do it.

**Comment by martindholmes** [comment]
Documentation added in commit 23231ac.
